word_endings:
  - ovski
  - evski
  - anski
  - stvo
  - štvo
  - šen
  - ski
  - ček
  - ovm
  - ega
  - ovi
  - ijo
  - ija
  - ema
  - ste
  - ejo
  - ite
  - ila
  - šče
  - ški
  - ost
  - ast
  - len
  - ven
  - vna
  - čan
  - iti
  - al
  - ah
  - ih
  - iv
  - eg
  - ja
  - je
  - em
  - en
  - ev
  - ov
  - jo
  - ma
  - mi
  - eh
  - ij
  - om
  - do
  - oč
  - ti
  - il
  - ec
  - ka
  - in
  - an
  - at
  - ir
  - š
  - m
  - c
  - a
  - e
  - i
  - o
  - u